#pragma once



const char* _data_object_final_private_h = 

"                                                                                                                                            \n"
"#pragma once                                                                                                                                \n"
"                                                                                                                                            \n"
"#include <glib-object.h>                                                                                                                    \n"
"                                                                                                                                            \n"
"G_BEGIN_DECLS                                                                                                                               \n"
"                                                                                                                                            \n"
"#define NAMESPACE_TYPE_OBJECTNAME (namespace_objectname_get_type())                                                                         \n"
"G_DECLARE_FINAL_TYPE(NamespaceObjectName,namespace_objectname,NAMESPACE,OBJECTNAME,PNamespacePObjectName)                                   \n"
"                                                                                                                                            \n"
"typedef struct _NamespaceObjectNamePrivate NamespaceObjectNamePrivate;                                                                      \n"
"                                                                                                                                            \n"
"typedef struct _NamespaceObjectName {                                                                                                       \n"
"    PNamespacePObjectName parent_instance;                                                                                                  \n"
"    NamespaceObjectNamePrivate* priv;                                                                                                       \n"
"} NamespaceObjectName;                                                                                                                      \n"
"                                                                                                                                            \n"
"/* For use with derivable type                                                                                                              \n"
" *                                                                                                                                          \n"
"typedef struct _NamespaceObjectNameClass {                                                                                                  \n"
"    PNamespacePObjectNameClass parent_class;                                                                                                \n"
"} NamespaceObjectNameClass;                                                                                                                 \n"
"*/                                                                                                                                          \n"
"                                                                                                                                            \n"
"                                                                                                                                            \n"
"/*  *******************************************  *                                                                                          \n"
" *  NamespaceObjectName Public Methods           *                                                                                          \n"
" *  *******************************************  */                                                                                         \n"
"                                                                                                                                            \n"
"NamespaceObjectName* namespace_objectname_new();                                                                                            \n"
"                                                                                                                                            \n"
"                                                                                                                                            \n"
"G_END_DECLS                                                                                                                                 \n"
;

size_t _size_object_final_private_h = 4653;



const char* _data_object_final_private_c = 

"#include \"namespace_objectname.h\"                                                                                                         \n"
"                                                                                                                                            \n"
"typedef struct _NamespaceObjectNamePrivate {                                                                                                \n"
"                                                                                                                                            \n"
"} NamespaceObjectNamePrivate;                                                                                                               \n"
"                                                                                                                                            \n"
"G_DEFINE_TYPE_WITH_PRIVATE(NamespaceObjectName,namespace_objectname,PNAMESPACE_TYPE_POBJECTNAME)                                            \n"
"                                                                                                                                            \n"
"                                                                                                                                            \n"
"void namespace_objectname_dispose(GObject* g_object){                                                                                       \n"
"                                                                                                                                            \n"
"    NamespaceObjectName* self = NAMESPACE_OBJECTNAME(g_object);                                                                             \n"
"                                                                                                                                            \n"
"                                                                                                                                            \n"
"    G_OBJECT_CLASS(namespace_objectname_parent_class)->dispose(g_object);                                                                   \n"
"}                                                                                                                                           \n"
"                                                                                                                                            \n"
"void namespace_objectname_finalize(GObject* g_object){                                                                                      \n"
"                                                                                                                                            \n"
"    NamespaceObjectName* self = NAMESPACE_OBJECTNAME(g_object);                                                                             \n"
"                                                                                                                                            \n"
"                                                                                                                                            \n"
"    G_OBJECT_CLASS(namespace_objectname_parent_class)->finalize(g_object);                                                                  \n"
"}                                                                                                                                           \n"
"                                                                                                                                            \n"
"void namespace_objectname_class_init(NamespaceObjectNameClass* klass){                                                                      \n"
"                                                                                                                                            \n"
"    GObjectClass* g_object_class = G_OBJECT_CLASS(klass);                                                                                   \n"
"                                                                                                                                            \n"
"    if ( namespace_objectname_parent_class == NULL)                                                                                         \n"
"        namespace_objectname_parent_class = g_type_class_peek_parent(klass);                                                                \n"
"                                                                                                                                            \n"
"    g_object_class->dispose = namespace_objectname_dispose;                                                                                 \n"
"    g_object_class->finalize = namespace_objectname_finalize;                                                                               \n"
"                                                                                                                                            \n"
"    /* Override functions here */                                                                                                           \n"
"                                                                                                                                            \n"
"                                                                                                                                            \n"
"}                                                                                                                                           \n"
"                                                                                                                                            \n"
"void namespace_objectname_init(NamespaceObjectName* self){                                                                                  \n"
"                                                                                                                                            \n"
"    self->priv = G_TYPE_INSTANCE_GET_PRIVATE(self,NAMESPACE_TYPE_OBJECTNAME,NamespaceObjectNamePrivate);                                    \n"
"                                                                                                                                            \n"
"    // Init your instance Here                                                                                                              \n"
"                                                                                                                                            \n"
"                                                                                                                                            \n"
"}                                                                                                                                           \n"
"                                                                                                                                            \n"
"                                                                                                                                            \n"
"NamespaceObjectName* namespace_objectname_new(){                                                                                            \n"
"    return g_object_new(NAMESPACE_TYPE_OBJECTNAME,NULL);                                                                                    \n"
"}                                                                                                                                           \n"
"                                                                                                                                            \n"
;

size_t _size_object_final_private_c = 7614;

